version: "3.8"
services:
  url-shortner-api:
    container_name: shortner_api
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - api_db
    networks:
      - app_network

  api_nginx:
    container_name: api_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - url-shortner-api
    environment:
      NGINX_FPM_HOST: url-shortner-api
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  api_db:
    container_name: api_db
    image: mysql:8.0.20
    command: [ "--max_connections=1000" ]
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: shortner_api
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    networks:
      - app_network

  api_redis:
    container_name: api_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge